"""Legal QA API service boundary and deterministic workflow adapter."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field, replace
from enum import StrEnum
from time import perf_counter
from typing import Protocol
from uuid import uuid4

from pydantic import HttpUrl, TypeAdapter, ValidationError

from src.api.schemas import (
    CitationDTO,
    EvidenceDTO,
    LegalQADecision,
    LegalQARequest,
    LegalQAResponse,
    ResponseMetadataDTO,
)
from src.services.legal_qa_context import (
    LegalQAContextPreparer,
    PreparedLegalQAContext,
)

_HTTP_URL_ADAPTER = TypeAdapter(HttpUrl)

LegalQATimingLogger = Callable[[str, str | None, int, int, str | None], None]


class LegalQAWorkflowDecision(StrEnum):
    """Internal decision values returned by a legal QA workflow."""

    ANSWERED = "answered"
    ANSWERED_WITH_CAUTION = "answered_with_caution"
    FALLBACK = "fallback"


@dataclass(frozen=True)
class LegalQAWorkflowRequest:
    """Internal request passed from the API service to a legal QA workflow.

    Attributes:
        request_id: Opaque request identifier generated by the service boundary.
        question: Validated and stripped Vietnamese legal question.
        top_k: Requested evidence count for the workflow.
        include_debug: Reserved for future debug/admin behavior.
    """

    request_id: str
    question: str
    top_k: int
    context: PreparedLegalQAContext | None = None
    include_debug: bool = False
    timing_logger: LegalQATimingLogger | None = field(default=None, repr=False, compare=False)
    timing_started_at: float | None = field(default=None, repr=False, compare=False)


@dataclass(frozen=True)
class LegalQAWorkflowCitation:
    """Citation-ready child evidence reference returned by a workflow."""

    evidence_id: str
    chunk_id: str
    law_id: str
    law_name: str
    citation: str
    source_url: str
    hierarchy_path: str


@dataclass(frozen=True)
class LegalQAWorkflowEvidence:
    """Selected citable child evidence returned by a workflow."""

    evidence_id: str
    chunk_id: str
    law_id: str
    law_name: str
    citation: str
    text: str
    source_url: str
    score: float


@dataclass(frozen=True)
class LegalQAWorkflowMetadata:
    """Workflow metadata safe to expose through the public API response."""

    retrieval_strategy: str = "coverage_aware_quota"
    model: str | None = None
    reranking_used: bool = False
    latency_ms: int = 0
    conversation_context_used: bool = False
    conversation_context_message_count: int = 0
    follow_up_detected: bool = False
    retrieval_question_prepared: bool = False
    retrieval_mode: str = "hybrid"
    dense_retrieval_used: bool = False
    dense_retrieval_fallback_used: bool = False
    fallback_used: bool = False
    retriever_stage_failed: str | None = None
    embedding_model_cache_hit: bool = False
    embedding_model_loaded_before_request: bool = False
    model_cache_key: str | None = None


@dataclass(frozen=True)
class LegalQAWorkflowResult:
    """Internal result returned by a legal QA workflow.

    The result may represent an answered or fallback decision. Citations and evidence
    must describe selected child evidence only; parent context is auxiliary and not
    directly citable.
    """

    decision: LegalQAWorkflowDecision
    answer: str
    citations: list[LegalQAWorkflowCitation] = field(default_factory=list)
    evidence: list[LegalQAWorkflowEvidence] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    metadata: LegalQAWorkflowMetadata = field(default_factory=LegalQAWorkflowMetadata)


class LegalQAWorkflow(Protocol):
    """Protocol for future real or fake legal QA workflows."""

    def run(self, request: LegalQAWorkflowRequest) -> LegalQAWorkflowResult:
        """Run legal QA for a validated internal request.

        Args:
            request: Internal legal QA workflow request.

        Returns:
            Internal workflow result ready for API response mapping.
        """
        ...


@dataclass(frozen=True)
class LegalQAWarmupResult:
    """Sanitized warmup result for explicit embedding initialization."""

    warmed: bool
    elapsed_ms: int
    exception_class: str | None = None
    model_path_configured: bool = False
    model_path_exists: bool = False
    required_files_present: bool = False
    model_load_started: bool = False
    model_load_completed: bool = False
    model_load_timeout: bool = False
    encode_started: bool = False
    encode_completed: bool = False
    encode_timeout: bool = False
    cache_hit_before: bool = False
    cache_hit_after: bool = False
    model_cache_key: str | None = None


class LegalQAServiceError(RuntimeError):
    """Sanitized internal service failure with safe diagnostic metadata."""

    def __init__(
        self,
        *,
        failure_stage: str,
        original_exception: BaseException,
        request_id: str | None = None,
    ) -> None:
        self.failure_stage = _safe_failure_stage(original_exception, default=failure_stage)
        self.request_id = request_id
        self.exception_class = (
            type(original_exception).__name__
            if isinstance(original_exception, TimeoutError)
            else _root_exception_class(original_exception)
        )
        super().__init__(
            "Legal QA service failed "
            f"at stage {self.failure_stage} with exception class {self.exception_class}"
        )


class FakeLegalQAWorkflow:
    """Deterministic fake workflow for API contract tests and local development.

    This fake does not call Qdrant, OpenRouter, embedding models, rerankers, or
    evaluation workflows.
    """

    def run(self, request: LegalQAWorkflowRequest) -> LegalQAWorkflowResult:
        """Return deterministic citation-shaped data.

        Args:
            request: Internal legal QA workflow request.

        Returns:
            Answered workflow result with one citable child evidence unit.
        """
        citation = LegalQAWorkflowCitation(
            evidence_id="E1",
            chunk_id="stub-child-chunk-001",
            law_id="stub-law-001",
            law_name="Bộ luật Lao động",
            citation="Điều 35 Bộ luật Lao động",
            source_url="https://thuvienphapluat.vn/van-ban/Lao-dong-Tien-luong/",
            hierarchy_path="Điều 35",
        )
        evidence = LegalQAWorkflowEvidence(
            evidence_id=citation.evidence_id,
            chunk_id=citation.chunk_id,
            law_id=citation.law_id,
            law_name=citation.law_name,
            citation=citation.citation,
            text=(
                "Người lao động có quyền đơn phương chấm dứt hợp đồng lao động "
                "theo các trường hợp được pháp luật lao động quy định."
            ),
            source_url=citation.source_url,
            score=1.0,
        )
        return LegalQAWorkflowResult(
            decision=LegalQAWorkflowDecision.ANSWERED,
            answer=(
                "Đây là phản hồi mẫu từ API stub. Khi tích hợp RAG thật, câu trả lời "
                "sẽ chỉ dựa trên bằng chứng pháp lý được chọn và có thể trích dẫn."
            ),
            citations=[citation],
            evidence=[evidence],
            warnings=[],
            metadata=LegalQAWorkflowMetadata(
                retrieval_strategy="coverage_aware_quota",
                model="stub",
                reranking_used=False,
                latency_ms=0,
            ),
        )


class LegalQAService:
    """Service boundary between FastAPI routes and legal QA workflows.

    The service owns request ID creation, workflow invocation, and mapping internal
    workflow models into stable API DTOs. The default fake workflow is deterministic
    and does not call external services.
    """

    def __init__(
        self,
        workflow: LegalQAWorkflow | None = None,
        context_preparer: LegalQAContextPreparer | None = None,
    ) -> None:
        self._workflow = workflow or FakeLegalQAWorkflow()
        self._context_preparer = context_preparer or LegalQAContextPreparer()

    @staticmethod
    def create_request_id() -> str:
        """Create an opaque request identifier.

        Returns:
            Request identifier suitable for client correlation.
        """
        return str(uuid4())

    def answer(
        self,
        request: LegalQARequest,
        *,
        timing_logger: LegalQATimingLogger | None = None,
    ) -> LegalQAResponse:
        """Run the configured workflow and map its result to the API contract.

        Args:
            request: Validated legal QA request.
            timing_logger: Optional sanitized stage timing sink. It must not log
                question text, conversation text, retrieved evidence, provider
                responses, secrets, headers, or cookies.

        Returns:
            Stable API response preserving request ID, citations, optional evidence,
            warnings, and safe workflow metadata.
        """
        request_id = self.create_request_id()
        timing_started_at = perf_counter()
        try:
            stage_started_at = perf_counter()
            prepared_context = self._context_preparer.prepare(request)
        except Exception as exc:
            _emit_timing(
                timing_logger=timing_logger,
                stage="conversation_context_loading",
                request_id=request_id,
                stage_started_at=stage_started_at,
                timing_started_at=timing_started_at,
                exception_class=_root_exception_class(exc),
            )
            raise LegalQAServiceError(
                failure_stage="context_preparation",
                original_exception=exc,
                request_id=request_id,
            ) from exc
        _emit_timing(
            timing_logger=timing_logger,
            stage="conversation_context_loading",
            request_id=request_id,
            stage_started_at=stage_started_at,
            timing_started_at=timing_started_at,
        )
        _emit_timing(
            timing_logger=timing_logger,
            stage="retrieval_question_preparation",
            request_id=request_id,
            stage_started_at=None,
            timing_started_at=timing_started_at,
        )

        workflow_request = LegalQAWorkflowRequest(
            request_id=request_id,
            question=prepared_context.effective_question,
            top_k=request.top_k,
            context=prepared_context,
            include_debug=request.include_debug,
            timing_logger=timing_logger,
            timing_started_at=timing_started_at,
        )
        try:
            result = self._workflow.run(workflow_request)
        except Exception as exc:
            _emit_timing(
                timing_logger=timing_logger,
                stage="workflow_run",
                request_id=request_id,
                stage_started_at=None,
                timing_started_at=timing_started_at,
                exception_class=_root_exception_class(exc),
            )
            raise LegalQAServiceError(
                failure_stage="workflow_run",
                original_exception=exc,
                request_id=request_id,
            ) from exc

        try:
            stage_started_at = perf_counter()
            result = replace(
                result,
                metadata=replace(
                    result.metadata,
                    conversation_context_used=prepared_context.context_used,
                    conversation_context_message_count=prepared_context.message_count,
                    follow_up_detected=prepared_context.follow_up_detected,
                    retrieval_question_prepared=(
                        prepared_context.retrieval_question != prepared_context.original_question
                    ),
                ),
            )
            response = map_workflow_result_to_response(
                request_id=request_id,
                result=result,
                include_evidence=request.include_evidence,
            )
            _emit_timing(
                timing_logger=timing_logger,
                stage="response_mapping",
                request_id=request_id,
                stage_started_at=stage_started_at,
                timing_started_at=timing_started_at,
            )
            return response
        except Exception as exc:
            _emit_timing(
                timing_logger=timing_logger,
                stage="response_mapping",
                request_id=request_id,
                stage_started_at=stage_started_at,
                timing_started_at=timing_started_at,
                exception_class=_root_exception_class(exc),
            )
            raise LegalQAServiceError(
                failure_stage="response_mapping",
                original_exception=exc,
                request_id=request_id,
            ) from exc

    def warmup_embedding(self) -> LegalQAWarmupResult:
        """Warm the embedding dependency when the workflow supports it.

        Returns:
            Sanitized warmup status. This method does not expose prompt text,
            retrieved evidence, generated answers, secrets, or raw exception text.
        """
        started_at = perf_counter()
        model_status_before = self.embedding_model_status()
        warmup = getattr(self._workflow, "warmup_embedding", None)
        if warmup is None or not callable(warmup):
            cache_hit = bool(model_status_before.get("embedding_model_cache_hit", False))
            return LegalQAWarmupResult(
                warmed=False,
                elapsed_ms=0,
                cache_hit_before=cache_hit,
                cache_hit_after=cache_hit,
                model_cache_key=_safe_metadata_string(model_status_before.get("model_cache_key")),
                **_path_status_kwargs(model_status_before),
            )
        try:
            warmup()
        except Exception as exc:
            exception_class = _root_exception_class(exc)
            failure_stage = _safe_failure_stage(exc, default="")
            model_status_after = self.embedding_model_status()
            cache_hit_before = bool(model_status_before.get("embedding_model_cache_hit", False))
            cache_hit_after = bool(model_status_after.get("embedding_model_cache_hit", False))
            return LegalQAWarmupResult(
                warmed=False,
                elapsed_ms=int((perf_counter() - started_at) * 1000),
                exception_class=exception_class,
                model_load_started=not cache_hit_before,
                model_load_completed=cache_hit_after,
                model_load_timeout=failure_stage == "embedding_model_load_timeout",
                encode_started=cache_hit_after,
                encode_completed=False,
                encode_timeout=failure_stage == "query_embedding_timeout",
                cache_hit_before=cache_hit_before,
                cache_hit_after=cache_hit_after,
                model_cache_key=_safe_metadata_string(
                    model_status_after.get("model_cache_key")
                    or model_status_before.get("model_cache_key")
                ),
                **_path_status_kwargs(model_status_before),
            )
        model_status_after = self.embedding_model_status()
        cache_hit_before = bool(model_status_before.get("embedding_model_cache_hit", False))
        cache_hit_after = bool(model_status_after.get("embedding_model_cache_hit", False))
        return LegalQAWarmupResult(
            warmed=True,
            elapsed_ms=int((perf_counter() - started_at) * 1000),
            model_load_started=not cache_hit_before,
            model_load_completed=cache_hit_after,
            encode_started=True,
            encode_completed=True,
            cache_hit_before=cache_hit_before,
            cache_hit_after=cache_hit_after,
            model_cache_key=_safe_metadata_string(
                model_status_after.get("model_cache_key")
                or model_status_before.get("model_cache_key")
            ),
            **_path_status_kwargs(model_status_before),
        )

    def embedding_model_status(self) -> dict[str, object]:
        """Return shallow embedding model status without loading model weights."""
        status = getattr(self._workflow, "embedding_model_status", None)
        if status is None or not callable(status):
            return {
                "model_path_configured": False,
                "model_path_exists": False,
                "required_files_present": False,
            }
        raw_status = status()
        if not isinstance(raw_status, dict):
            raw_status = {}
        return {
            "model_path_configured": bool(raw_status.get("model_path_configured", False)),
            "model_path_exists": bool(raw_status.get("model_path_exists", False)),
            "required_files_present": bool(raw_status.get("required_files_present", False)),
            "embedding_model_cache_hit": bool(raw_status.get("embedding_model_cache_hit", False)),
            "model_cache_key": _safe_metadata_string(raw_status.get("model_cache_key")),
        }


def map_workflow_result_to_response(
    *,
    request_id: str,
    result: LegalQAWorkflowResult,
    include_evidence: bool,
) -> LegalQAResponse:
    """Map an internal workflow result into the stable public API response.

    Args:
        request_id: Request identifier generated at the API service boundary.
        result: Internal workflow result.
        include_evidence: Whether to expose selected evidence DTOs.

    Returns:
        API response DTO. Fallback results intentionally omit citations and evidence
        to avoid presenting insufficient evidence as a confident legal basis.
    """
    if result.decision == LegalQAWorkflowDecision.FALLBACK:
        return _fallback_response(
            request_id=request_id,
            answer=result.answer,
            warnings=result.warnings,
            metadata=result.metadata,
        )

    metadata_issues = _answer_metadata_issues(result)
    if metadata_issues:
        return _fallback_response(
            request_id=request_id,
            answer="Không tìm thấy đủ căn cứ pháp lý trong nguồn hiện có.",
            warnings=[*result.warnings, *metadata_issues],
            metadata=result.metadata,
        )

    decision = (
        LegalQADecision.ANSWERED_WITH_CAUTION
        if result.decision == LegalQAWorkflowDecision.ANSWERED_WITH_CAUTION
        else LegalQADecision.ANSWERED
    )
    return LegalQAResponse(
        request_id=request_id,
        decision=decision,
        answer=result.answer,
        citations=[
            CitationDTO(
                evidence_id=citation.evidence_id,
                chunk_id=citation.chunk_id,
                law_id=citation.law_id,
                law_name=citation.law_name,
                citation=citation.citation,
                source_url=citation.source_url,
                hierarchy_path=citation.hierarchy_path,
            )
            for citation in result.citations
        ],
        evidence=[
            EvidenceDTO(
                evidence_id=evidence.evidence_id,
                chunk_id=evidence.chunk_id,
                law_id=evidence.law_id,
                law_name=evidence.law_name,
                citation=evidence.citation,
                text=evidence.text,
                source_url=evidence.source_url,
                score=evidence.score,
            )
            for evidence in result.evidence
        ]
        if include_evidence
        else [],
        warnings=list(result.warnings),
        metadata=_map_metadata(result.metadata),
    )


def _fallback_response(
    *,
    request_id: str,
    answer: str,
    warnings: list[str],
    metadata: LegalQAWorkflowMetadata,
) -> LegalQAResponse:
    safe_warnings = list(warnings)
    if "fallback" not in safe_warnings:
        safe_warnings.append("fallback")
    return LegalQAResponse(
        request_id=request_id,
        decision=LegalQADecision.FALLBACK,
        answer=answer,
        citations=[],
        evidence=[],
        warnings=safe_warnings,
        metadata=_map_metadata(metadata),
    )


def _answer_metadata_issues(result: LegalQAWorkflowResult) -> list[str]:
    if not result.citations:
        return ["missing_citations"]
    issues: list[str] = []
    for citation in result.citations:
        if not citation.chunk_id:
            issues.append("missing_citation_chunk_id")
        if not citation.law_id:
            issues.append("missing_citation_law_id")
        if not citation.citation:
            issues.append("missing_citation_label")
        if not citation.source_url:
            issues.append("missing_citation_source_url")
        elif not _is_valid_http_url(citation.source_url):
            issues.append("invalid_citation_source_url")
    for evidence in result.evidence:
        if not evidence.text:
            issues.append("missing_evidence_text")
        if not evidence.source_url:
            issues.append("missing_evidence_source_url")
        elif not _is_valid_http_url(evidence.source_url):
            issues.append("invalid_evidence_source_url")
    return list(dict.fromkeys(issues))


def _is_valid_http_url(value: str) -> bool:
    try:
        _HTTP_URL_ADAPTER.validate_python(value)
    except ValidationError:
        return False
    return True


def _root_exception_class(exc: BaseException) -> str:
    root = exc
    seen: set[int] = set()
    while root.__cause__ is not None and id(root.__cause__) not in seen:
        seen.add(id(root))
        root = root.__cause__
    return type(root).__name__


def _safe_failure_stage(exc: BaseException, *, default: str) -> str:
    stage = getattr(exc, "failure_stage", None)
    if isinstance(stage, str) and stage.replace("_", "").isalnum():
        return stage
    return default


def _safe_metadata_string(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    stripped = value.strip()
    if not stripped:
        return None
    if not all(character.isalnum() or character in {":", "_", "-"} for character in stripped):
        return None
    return stripped


def _emit_timing(
    *,
    timing_logger: LegalQATimingLogger | None,
    stage: str,
    request_id: str | None,
    stage_started_at: float | None,
    timing_started_at: float,
    exception_class: str | None = None,
) -> None:
    if timing_logger is None:
        return
    now = perf_counter()
    elapsed_ms = int((now - stage_started_at) * 1000) if stage_started_at is not None else 0
    total_elapsed_ms = int((now - timing_started_at) * 1000)
    timing_logger(stage, request_id, elapsed_ms, total_elapsed_ms, exception_class)


def _map_metadata(metadata: LegalQAWorkflowMetadata) -> ResponseMetadataDTO:
    """Map safe internal workflow metadata into the public API metadata DTO."""
    return ResponseMetadataDTO(
        retrieval_strategy=metadata.retrieval_strategy,
        model=metadata.model,
        reranking_used=metadata.reranking_used,
        latency_ms=metadata.latency_ms,
        conversation_context_used=metadata.conversation_context_used,
        conversation_context_message_count=(metadata.conversation_context_message_count),
        follow_up_detected=metadata.follow_up_detected,
        retrieval_question_prepared=metadata.retrieval_question_prepared,
        retrieval_mode=metadata.retrieval_mode,
        dense_retrieval_used=metadata.dense_retrieval_used,
        dense_retrieval_fallback_used=metadata.dense_retrieval_fallback_used,
        fallback_used=metadata.fallback_used,
        retriever_stage_failed=metadata.retriever_stage_failed,
        embedding_model_cache_hit=metadata.embedding_model_cache_hit,
        embedding_model_loaded_before_request=metadata.embedding_model_loaded_before_request,
        model_cache_key=metadata.model_cache_key,
    )


def _path_status_kwargs(status: dict[str, object]) -> dict[str, bool]:
    return {
        "model_path_configured": bool(status.get("model_path_configured", False)),
        "model_path_exists": bool(status.get("model_path_exists", False)),
        "required_files_present": bool(status.get("required_files_present", False)),
    }
