"""Legal QA API service boundary and deterministic workflow adapter."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Protocol
from uuid import uuid4

from src.api.schemas import (
    CitationDTO,
    EvidenceDTO,
    LegalQADecision,
    LegalQARequest,
    LegalQAResponse,
    ResponseMetadataDTO,
)
from src.services.legal_qa_context import (
    LegalQAContextPreparer,
    PreparedLegalQAContext,
)


class LegalQAWorkflowDecision(StrEnum):
    """Internal decision values returned by a legal QA workflow."""

    ANSWERED = "answered"
    FALLBACK = "fallback"


@dataclass(frozen=True)
class LegalQAWorkflowRequest:
    """Internal request passed from the API service to a legal QA workflow.

    Attributes:
        request_id: Opaque request identifier generated by the service boundary.
        question: Validated and stripped Vietnamese legal question.
        top_k: Requested evidence count for the workflow.
        include_debug: Reserved for future debug/admin behavior.
    """

    request_id: str
    question: str
    top_k: int
    context: PreparedLegalQAContext | None = None
    include_debug: bool = False


@dataclass(frozen=True)
class LegalQAWorkflowCitation:
    """Citation-ready child evidence reference returned by a workflow."""

    evidence_id: str
    chunk_id: str
    law_id: str
    law_name: str
    citation: str
    source_url: str
    hierarchy_path: str


@dataclass(frozen=True)
class LegalQAWorkflowEvidence:
    """Selected citable child evidence returned by a workflow."""

    evidence_id: str
    chunk_id: str
    law_id: str
    law_name: str
    citation: str
    text: str
    source_url: str
    score: float


@dataclass(frozen=True)
class LegalQAWorkflowMetadata:
    """Workflow metadata safe to expose through the public API response."""

    retrieval_strategy: str = "coverage_aware_quota"
    model: str | None = None
    reranking_used: bool = False
    latency_ms: int = 0


@dataclass(frozen=True)
class LegalQAWorkflowResult:
    """Internal result returned by a legal QA workflow.

    The result may represent an answered or fallback decision. Citations and evidence
    must describe selected child evidence only; parent context is auxiliary and not
    directly citable.
    """

    decision: LegalQAWorkflowDecision
    answer: str
    citations: list[LegalQAWorkflowCitation] = field(default_factory=list)
    evidence: list[LegalQAWorkflowEvidence] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    metadata: LegalQAWorkflowMetadata = field(default_factory=LegalQAWorkflowMetadata)


class LegalQAWorkflow(Protocol):
    """Protocol for future real or fake legal QA workflows."""

    def run(self, request: LegalQAWorkflowRequest) -> LegalQAWorkflowResult:
        """Run legal QA for a validated internal request.

        Args:
            request: Internal legal QA workflow request.

        Returns:
            Internal workflow result ready for API response mapping.
        """
        ...


class FakeLegalQAWorkflow:
    """Deterministic fake workflow for API contract tests and local development.

    This fake does not call Qdrant, OpenRouter, embedding models, rerankers, or
    evaluation workflows.
    """

    def run(self, request: LegalQAWorkflowRequest) -> LegalQAWorkflowResult:
        """Return deterministic citation-shaped data.

        Args:
            request: Internal legal QA workflow request.

        Returns:
            Answered workflow result with one citable child evidence unit.
        """
        citation = LegalQAWorkflowCitation(
            evidence_id="E1",
            chunk_id="stub-child-chunk-001",
            law_id="stub-law-001",
            law_name="Bộ luật Lao động",
            citation="Điều 35 Bộ luật Lao động",
            source_url="https://thuvienphapluat.vn/van-ban/Lao-dong-Tien-luong/",
            hierarchy_path="Điều 35",
        )
        evidence = LegalQAWorkflowEvidence(
            evidence_id=citation.evidence_id,
            chunk_id=citation.chunk_id,
            law_id=citation.law_id,
            law_name=citation.law_name,
            citation=citation.citation,
            text=(
                "Người lao động có quyền đơn phương chấm dứt hợp đồng lao động "
                "theo các trường hợp được pháp luật lao động quy định."
            ),
            source_url=citation.source_url,
            score=1.0,
        )
        return LegalQAWorkflowResult(
            decision=LegalQAWorkflowDecision.ANSWERED,
            answer=(
                "Đây là phản hồi mẫu từ API stub. Khi tích hợp RAG thật, câu trả lời "
                "sẽ chỉ dựa trên bằng chứng pháp lý được chọn và có thể trích dẫn."
            ),
            citations=[citation],
            evidence=[evidence],
            warnings=[],
            metadata=LegalQAWorkflowMetadata(
                retrieval_strategy="coverage_aware_quota",
                model="stub",
                reranking_used=False,
                latency_ms=0,
            ),
        )


class LegalQAService:
    """Service boundary between FastAPI routes and legal QA workflows.

    The service owns request ID creation, workflow invocation, and mapping internal
    workflow models into stable API DTOs. The default fake workflow is deterministic
    and does not call external services.
    """

    def __init__(
        self,
        workflow: LegalQAWorkflow | None = None,
        context_preparer: LegalQAContextPreparer | None = None,
    ) -> None:
        self._workflow = workflow or FakeLegalQAWorkflow()
        self._context_preparer = context_preparer or LegalQAContextPreparer()

    @staticmethod
    def create_request_id() -> str:
        """Create an opaque request identifier.

        Returns:
            Request identifier suitable for client correlation.
        """
        return str(uuid4())

    def answer(self, request: LegalQARequest) -> LegalQAResponse:
        """Run the configured workflow and map its result to the API contract.

        Args:
            request: Validated legal QA request.

        Returns:
            Stable API response preserving request ID, citations, optional evidence,
            warnings, and safe workflow metadata.
        """
        request_id = self.create_request_id()
        prepared_context = self._context_preparer.prepare(request)
        workflow_request = LegalQAWorkflowRequest(
            request_id=request_id,
            question=prepared_context.effective_question,
            top_k=request.top_k,
            context=prepared_context,
            include_debug=request.include_debug,
        )
        result = self._workflow.run(workflow_request)
        return map_workflow_result_to_response(
            request_id=request_id,
            result=result,
            include_evidence=request.include_evidence,
        )


def map_workflow_result_to_response(
    *,
    request_id: str,
    result: LegalQAWorkflowResult,
    include_evidence: bool,
) -> LegalQAResponse:
    """Map an internal workflow result into the stable public API response.

    Args:
        request_id: Request identifier generated at the API service boundary.
        result: Internal workflow result.
        include_evidence: Whether to expose selected evidence DTOs.

    Returns:
        API response DTO. Fallback results intentionally omit citations and evidence
        to avoid presenting insufficient evidence as a confident legal basis.
    """
    if result.decision == LegalQAWorkflowDecision.FALLBACK:
        warnings = list(result.warnings)
        if "fallback" not in warnings:
            warnings.append("fallback")
        return LegalQAResponse(
            request_id=request_id,
            decision=LegalQADecision.FALLBACK,
            answer=result.answer,
            citations=[],
            evidence=[],
            warnings=warnings,
            metadata=_map_metadata(result.metadata),
        )

    return LegalQAResponse(
        request_id=request_id,
        decision=LegalQADecision.ANSWERED,
        answer=result.answer,
        citations=[
            CitationDTO(
                evidence_id=citation.evidence_id,
                chunk_id=citation.chunk_id,
                law_id=citation.law_id,
                law_name=citation.law_name,
                citation=citation.citation,
                source_url=citation.source_url,
                hierarchy_path=citation.hierarchy_path,
            )
            for citation in result.citations
        ],
        evidence=[
            EvidenceDTO(
                evidence_id=evidence.evidence_id,
                chunk_id=evidence.chunk_id,
                law_id=evidence.law_id,
                law_name=evidence.law_name,
                citation=evidence.citation,
                text=evidence.text,
                source_url=evidence.source_url,
                score=evidence.score,
            )
            for evidence in result.evidence
        ]
        if include_evidence
        else [],
        warnings=list(result.warnings),
        metadata=_map_metadata(result.metadata),
    )


def _map_metadata(metadata: LegalQAWorkflowMetadata) -> ResponseMetadataDTO:
    """Map safe internal workflow metadata into the public API metadata DTO."""
    return ResponseMetadataDTO(
        retrieval_strategy=metadata.retrieval_strategy,
        model=metadata.model,
        reranking_used=metadata.reranking_used,
        latency_ms=metadata.latency_ms,
    )
