"""Retrieval domain components."""

from __future__ import annotations

from src.retrieval.dense_retriever import DenseRetriever, DenseRetrieverError
from src.retrieval.evaluation import (
    DenseRetrievalEvaluationReport,
    ExpectedTarget,
    ManualRetrievalQuery,
    PerQueryEvaluationResult,
    evaluate_dense_retrieval,
    load_manual_retrieval_queries,
)
from src.retrieval.evidence import (
    CitationScope,
    ContextAssemblyConfig,
    EvidenceBundle,
    EvidenceCitation,
    EvidencePacket,
    EvidenceSafetyIssue,
    EvidenceSafetyLevel,
    EvidenceText,
    ParentContextPolicy,
    build_evidence_bundle,
    build_evidence_packet,
)
from src.retrieval.generation import (
    CitationCheckResult,
    CitationIssue,
    CitationIssueSeverity,
    RagAnswerResult,
    RagCitation,
    RagGenerationConfig,
    UsedEvidence,
    build_fallback_result,
    check_generated_citations,
)
from src.retrieval.generation_evaluation import (
    GenerationEvalCaseResult,
    GenerationEvalQuery,
    GenerationEvalReport,
    GenerationValidationIssue,
    build_generation_eval_report,
    load_generation_eval_queries,
    validate_generation_result,
)
from src.retrieval.integration import (
    SelectionSmokeAggregate,
    SelectionSmokeError,
    SelectionSmokeEvidenceSummary,
    SelectionSmokeQueryResult,
    SelectionSmokeReport,
    aggregate_smoke_results,
    filter_query_records,
    run_selection_smoke_for_query,
    run_selection_smoke_suite,
)
from src.retrieval.llm_client import (
    LLMClientError,
    LLMMessage,
    LLMRequest,
    LLMResponse,
    LLMUsage,
    MockLLMClient,
    OpenRouterLLMClient,
)
from src.retrieval.models import RetrievalFilters, RetrievalQuery, RetrievalResult, RetrievedChunk
from src.retrieval.openrouter_config import (
    FALLBACK_OPENROUTER_BASE_URL,
    FALLBACK_OPENROUTER_DEV_MODEL,
    FALLBACK_OPENROUTER_MODEL,
    OpenRouterConfig,
    OpenRouterRuntimeSettings,
    load_openrouter_config,
    load_project_dotenv,
    resolve_openrouter_settings,
)
from src.retrieval.prompting import PromptEvidence, RagPrompt, build_naive_rag_prompt
from src.retrieval.rag_pipeline import run_naive_rag
from src.retrieval.selection import (
    AnswerabilityDecision,
    EvidenceRejectionReason,
    EvidenceSelectionConfig,
    EvidenceSelectionResult,
    FallbackReason,
    FallbackReasonCode,
    RejectedEvidence,
    SelectedEvidence,
    SelectionWarning,
    select_evidence_for_answer,
)

__all__ = [
    "AnswerabilityDecision",
    "CitationCheckResult",
    "CitationIssue",
    "CitationIssueSeverity",
    "CitationScope",
    "ContextAssemblyConfig",
    "DenseRetrievalEvaluationReport",
    "DenseRetriever",
    "DenseRetrieverError",
    "EvidenceBundle",
    "EvidenceCitation",
    "EvidencePacket",
    "EvidenceRejectionReason",
    "EvidenceSafetyIssue",
    "EvidenceSafetyLevel",
    "EvidenceSelectionConfig",
    "EvidenceSelectionResult",
    "EvidenceText",
    "ExpectedTarget",
    "FallbackReason",
    "FallbackReasonCode",
    "FALLBACK_OPENROUTER_BASE_URL",
    "FALLBACK_OPENROUTER_DEV_MODEL",
    "FALLBACK_OPENROUTER_MODEL",
    "GenerationEvalCaseResult",
    "GenerationEvalQuery",
    "GenerationEvalReport",
    "GenerationValidationIssue",
    "LLMClientError",
    "LLMMessage",
    "LLMRequest",
    "LLMResponse",
    "LLMUsage",
    "ManualRetrievalQuery",
    "MockLLMClient",
    "OpenRouterLLMClient",
    "OpenRouterConfig",
    "OpenRouterRuntimeSettings",
    "ParentContextPolicy",
    "PerQueryEvaluationResult",
    "PromptEvidence",
    "RagAnswerResult",
    "RagCitation",
    "RagGenerationConfig",
    "RagPrompt",
    "RejectedEvidence",
    "RetrievedChunk",
    "RetrievalFilters",
    "RetrievalQuery",
    "RetrievalResult",
    "SelectedEvidence",
    "SelectionWarning",
    "SelectionSmokeAggregate",
    "SelectionSmokeError",
    "SelectionSmokeEvidenceSummary",
    "SelectionSmokeQueryResult",
    "SelectionSmokeReport",
    "aggregate_smoke_results",
    "build_evidence_bundle",
    "build_evidence_packet",
    "build_fallback_result",
    "build_generation_eval_report",
    "build_naive_rag_prompt",
    "check_generated_citations",
    "evaluate_dense_retrieval",
    "filter_query_records",
    "load_manual_retrieval_queries",
    "load_generation_eval_queries",
    "load_openrouter_config",
    "load_project_dotenv",
    "run_naive_rag",
    "run_selection_smoke_for_query",
    "run_selection_smoke_suite",
    "resolve_openrouter_settings",
    "select_evidence_for_answer",
    "validate_generation_result",
    "UsedEvidence",
]
